FROM python:3.11-slim
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libgl1-mesa-glx \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY requirements-flask.txt .
RUN pip install --no-cache-dir -r requirements-flask.txt
COPY . .
EXPOSE 5000
CMD ["python", "app.py"]